//
//  MDMViewController.m
//  MedMon
//
//  Created by Saurabh Rathod on 7/29/14.
//  Copyright (c) 2014 Health Information Management. All rights reserved.
//

#import "MDMViewController.h"
#import "MDMInputOutput.h"
#import "MDMPageTwoViewController.h"

//This is an easier way to declare a String.
NSString *frequent = @"Once A Day";
NSString *medName = @" ";
NSString *medDsc = @" ";
NSString *cTime = @" ";
NSString *sTime = @" ";

@interface MDMViewController ()

@end

@implementation MDMViewController

//This method is an override implementation method. It cannot be removed
- (id)initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibBundleOrNil
{
    //All this code is generated by Xcode.
    self = [super initWithNibName:nibNameOrNil bundle:nibBundleOrNil];
    if (self) {
        // Custom initialization
    }
    return self;
}

//Override implementation method.
- (void)viewDidLoad
{
    //Xcode generated code.
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    //Sets the scrollview to enable scrolling.
    [_scroller setScrollEnabled:YES];
    //Custom size for your scroll view.
    [_scroller setContentSize:CGSizeMake(320, 568)];
    //This is the array that is used for the PickerView. This array consists of all Strings.
    self.dayArray  = [[NSArray alloc]         initWithObjects:@"Once A Day",@"Twice A Day",@"Three Times A Day",@"Four Times A Day",@"Five Times A Day",@"Six Times A Day" , nil];
    
    //Allow the textfield variables to contact the View Controller, and not the Delegate.
    self.medName.delegate = self;
    self.medDsc.delegate = self;

}

//Override implementation method.
- (void)didReceiveMemoryWarning
{
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}



#pragma mark - Navigation

// In a storyboard-based application, you will often want to do a little preparation before navigation
- (void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender
{
    // Get the new view controller using [segue destinationViewController].
    [segue destinationViewController];
    // Pass the selected object to the new view controller.
}


// returns the number of 'columns' to display.
- (NSInteger)numberOfComponentsInPickerView:(UIPickerView *)pickerView
{
    return 1;
}

// returns the # of rows in each component..
- (NSInteger)pickerView:(UIPickerView *)pickerView numberOfRowsInComponent:(NSInteger)component
{
    return 6;
}

-(NSString *)pickerView:(UIPickerView *)pickerView titleForRow:(NSInteger)row   forComponent:(NSInteger)component
{
    return [self.dayArray objectAtIndex:row];
}
- (void)pickerView:(UIPickerView *)pickerView didSelectRow:(NSInteger)row   inComponent:(NSInteger)component
{
    //UI PickerView Selection Text
    switch(row)
    {
            
        case 0:
            self.timePerDay.text = @"Once A Day";
            //self.timePerDay.textColor = [UIColor colorWithRed:0.0f/255.0f green: 0.0f/255.0f blue:255.0f/255.0f alpha:255.0f/255.0f];
            break;
        case 1:
            self.timePerDay.text = @"Twice A Day";
            //self.timePerDay.textColor = [UIColor colorWithRed:0.0f/255.0f green: 255.0f/255.0f blue:0.0f/255.0f alpha:255.0f/255.0f];
            break;
        case 2:
            self.timePerDay.text = @"Three Times A Day";
            //self.timePerDay.textColor = [UIColor colorWithRed:205.0f/255.0f green:   140.0f/255.0f blue:31.0f/255.0f alpha:255.0f/255.0f];
            break;
        case 3:
            self.timePerDay.text = @"Four Times A Day";
            //self.timePerDay.textColor = [UIColor colorWithRed:255.0f/255.0f green:   0.0f/255.0f blue:255.0f/255.0f alpha:255.0f/255.0f];
            break;
        case 4:
            self.timePerDay.text = @"Five Times A Day";
            //self.timePerDay.textColor = [UIColor colorWithRed:255.0f/255.0f green:   0.0f/255.0f blue:0.0f/255.0f alpha:255.0f/255.0f];
            break;
        case 5:
            self.timePerDay.text = @"Six Times A Day";
            //self.timePerDay.textColor = [UIColor colorWithRed:255.0f/255.0f green:   255.0f/255.0f blue:0.0f/255.0f alpha:255.0f/255.0f];
            break;
    }
    
    //To test if the String Saves.
    //  if([medName isEqualToString:@"Sleeping Pill"])
    //  {
    //    NSLog(@"YESSSS");
    //  }
    
    
    
}



-(IBAction) saveAction: (UIButton *)sender
{
    
    MDMPageTwoViewController *pageTwo = [[MDMPageTwoViewController alloc] init];
    //Saves the Label and TextField to Strings
    frequent = self.timePerDay.text;
    medName = self.medName.text;
    medDsc = self.medDsc.text;
    
//  cTime = pageTwo->lblTime.text;
    
  //  cHour = [pageTwo updateTime2];
  //  int toInt = [cHour intValue];
  //  NSLog(@"%@",cHour);
  //  NSLog(@"toInt:%d", toInt);
    
    cTime = [pageTwo updateTime2];
    sTime = [pageTwo updateTime3];
    
    NSArray *foo = [cTime componentsSeparatedByString:@":"];
    NSArray *foo2 = [sTime componentsSeparatedByString:@" "];
    
    NSInteger cHour = [foo objectAtIndex: 0];
    //NSLog(@"%@",cHour);
    
    NSInteger cMin = [foo objectAtIndex: 1];
    //NSLog(@"%@",cMin);
    NSInteger cSec = [foo objectAtIndex:2];
    
    NSString *saveTime = [foo2 objectAtIndex: 0];
    //NSLog(@"%@",saveTime);
    NSString *timeOfDay = [foo2 objectAtIndex: 1];
    //NSLog(@"%@",timeOfDay);

    MDMInputOutput *writer = [[MDMInputOutput alloc] init];
    
    [writer write:@"tm.vpr" content:saveTime];
    [writer write:@"tm.vpr" content:timeOfDay];


    
    //This is how you "quickly" allocate and initialize an Object.
    //This is similar to:
    //MDMInputOutput writer = new MDMInputOutput(); in JAVA.
    if (medName == NULL || medDsc == NULL || [medName isEqual: @""] || [medDsc  isEqual: @""] )
    {
    
       UIAlertView *medAlert = [[UIAlertView alloc] initWithTitle:@"Name/Description Error"
                                                           message:@"Please enter medicine name and/or it's description."
                                                          delegate:nil
                                                 cancelButtonTitle:@"GOTCHA!"
                                                 otherButtonTitles:nil];
        [medAlert show];
        //[medAlert release];

        
    }
    else
    {
        
        
        //This is how you use a method. From the Object initialized.
        //This one uses "writer.write(String file, String content)" in JAVA form.
        [writer write:@"mdm.vpr" content:frequent];
        //This method reads the specified file and returns a String format.
        [writer read:@"mdm.vpr"];
        //This is a CONSOLE Logger. It behaves similar to System.out.print();
        NSLog([writer read:@"mdm.vpr"]);
       
        //NSLog(@"med.vpr");
        
        //Declare a String. Strings do not need to be allocated or initialized,
        //because they made it easier for us in iOS SDK 7.
        //This variable goes to the next line.
        NSString *nextLine = @"\n";
        
        //This concatenates multiple Strings and String Variables together.
        //So, to concatenate more than two strings, you need to use this method inside over and over.
        //This is the method: "[string1 stringByAppendingString: string2]"
        [writer write:@"med.vpr" content: [medName stringByAppendingString: [nextLine stringByAppendingString:  medDsc]]];
        //Used the read method from MDMInputOutput
        [writer read:@"med.vpr"];
        NSLog([writer read:@"med.vpr"]);
        
        /**
         [writer write:@"mdm.vpr" content:frequent];
         [writer read:@"mdm.vpr"];
         NSLog([writer read:@"mdm.vpr"]);
         **/
        
    }
    //[super removeFromParentViewController];
}

//This method allows non-iPad users to get rid of the keyboard by pressing the RETURN button.
- (BOOL) textFieldShouldReturn: (UITextField *) textField
{
    //this removes the textfield from activating the Keyboard (Focusing) when the page loads.
    [textField resignFirstResponder];
    //Does not allow the textfield to do anything when the page loads.
    return NO;
}

@end
